guardian/cloudwatch-logs-management

scripts/build.sh
src/app.ts
src/config.ts
src/shipLogEntries.ts
src/structuredFields.ts
template.yaml

A PR to assume a role when sending logs via kinesis.
This has required restructuring the code so that we do not need to assume the role on every execution (or get the kinesis client in all of the lambdas). the restructure has separated out a few concerns anyway which is helpful.

Change code to enable role assumption

---

template.yaml

I was tripped up when I chose a number which was not supported:
See [https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html)

Add valid values for RetentionInDays

---

src/shipLogEntries.ts

Some lines from lambda have four fields, tab separated. They are timestamp, id, level and message. This adds some extra processing to handle these in a useful way.

Parse log lines of the format from node

---

.gitignore
package-lock.json
src/shipLogEntries.ts

This commit adds some logging to show what is actually being sent to Kibana. This helps with identifying whether logs have successfully made their way to Kibana.

chore: Add more logging to track what is being sent to Kibana

---

README.md
riff-raff.yaml
template.yaml

This adds the `deploy` (deployTools) account to the list of accounts where this is rolled out to.
I've also made a small improvement to the readme to make new account deployment clearer.

Add deploy account

---

src/shipLogEntries.ts

Uses constructor `Buffer.from(...)` instead of `new Buffer(...)`. Change is on response to these log messages:
```
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
Resolves #25.

Don't use deprecated method for constructing a buffer

---

src/kinesis.ts
src/shipLogEntries.ts

Ensure that no more than 500 records are submitted in a PutRecords request. See in-line comments or #24 for more context.
Resolves #24.

PutRecords to submit at most 500 records per call

---

src/cloudwatch.ts

Under some circumstances you might end up with the target changing (i.e. if the Lambda is changed due to some type of redeployment). In this scenario we don't currently update the target as it already exists.
We should compare both the filter name and also the target of the filter so that we update when necessary.

If the target is different from the current target then update

---

src/shipLogEntries.ts

When a node lambda logs via stdout or stderr cloudwatch puts either INFO or ERROR into the log line. This is super helpful but some applications might like to provide an explicit level in the JSON message they send. If they do this then it should be honoured but at the moment the cloudwatch level takes precedence.
On PROD there are currently no WARN level messages but after deploying this there will be.
I expect errors and warnings in ELK to increase as we are preserving them properly.

If a level is provided then honour it

---

src/app.ts
src/config.ts
src/shipLogEntries.ts

Whilst some of the AWS SDK clients used maxRetries 10, some did not and errors were visible in central ELK. This restructures the code a little to consistently use a common configuration.
When deployed this should eliminate the invoke errors currently seen in the `set-log-shipping` lambda.
This ELK view should diminish to nothing: https://logs.gutools.co.uk/goto/875a22b0bea4e5545c1ff8b3d4474acf

Consistently use 10 retries for AWS SDK

---

template.yaml

The CreateLogGroup call was being done a lot to try and recreate existing logs (particularly in frontend). Looked briefly at trying to improve the pattern but this seems very difficult so here we are simply falling back on schedules only. Keep it simple I guess.
Fewer errors in the ELK console.

Disable events as they were firing far too noisily

---

src/logEntryProcessing.test.ts
src/logEntryProcessing.ts
src/shipLogEntries.ts

This PR is a continuation of https://github.com/guardian/cloudwatch-logs-management/pull/42:
* Moves some more of the testable code into its own file
* Adds unit tests for several functions
* Fixes a small bug found during unit test implementation - we were dropping the last character of the request ID
You might find it easier to review this commit by commit, as this demonstrates where code has simply been moved vs where I've made minor modifications to fix the aforementioned bug.
CI now runs these unit tests!
It should be easier and safer to refactor this code in the future. We should feel more confident when performing upgrades etc.
I didn't write any of the original code, so there is a risk that I have misunderstood the intent behind some of the functions or assumed that expected …

Unit test some of the log processing functionality

---

package-lock.json
package.json

Brings the project up to date with the latest TypeScript version, as per https://github.com/guardian/cloudwatch-logs-management/pull/42#discussion_r595816224.
Observe CI.
The lambdas should continue to function normally.
Although this is a major version upgrade [`there are no major breaking changes`](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/), so I think this is relatively low risk.

Upgrade to TypeScript 4.2.3

---

.github/dependabot.yml

As this repository does not run in a context that is accessible to users or external requests, the risk of running old versions of dependencies for a short time is minimal. Update Dependabot's configuration to run monthly to reduce the frequency of PRs by a quarter and thus require less commitment from the team.

chore: Run Dependabot monthly

---

template.yaml

By setting the `AllowedValues` of the `Stage` param we prevent Riff-Raff from deploying to any stage other than PROD.
This is because we've seen bad things happen when multiple instances of the lambdas exist.
See https://docs.google.com/document/d/1HNEo6UKQ-JhoXHp0mr-KuGC1Ra_8_BfwSuPq3VgO0AI/edit#

fix: Restrict the values of `Stage` CFN Param

---

template.yaml

This PR prevents the ship log entries function from logging to CloudWatch in order to reduce the chances that we can accidentally create a feedback loop.
Unfortunately there is no easy way to turn off CloudWatch logging for a lambda so we have used [IAM permissions to achieve this goal](https://stackoverflow.com/a/53909607/15960596).
We have [deployed this change](https://riffraff.gutools.co.uk/deployment/view/1a4da427-4a4b-482c-bf9e-5560dd874838) to the `deployTools` account (only) and confirmed that:
1. [CloudWatch logs for this lambda stop](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fdeploy-PROD-cloudwatch-logs-man-ShipLogEntriesFunc-GUUHQH6VZMM0/log-events$3Fstart$3D1635943500000$26end$3D1635948000000) …

Prevent ship log entries lambda from logging to CloudWatch

---

README.md
src/app.ts
src/ecs.ts
src/structuredFields.ts
template.yaml

On investigations we're making quite significant use of ECS tasks. These by default log to cloudwatch. By modifying the `ShippingPrefix` parameter of the investigations cloudwatch-logs-management stack we can get them into ELK, but without any tags. 
What this PR does is get the tagging to work - matching the tags on a task definition to the associated output log groups.
This is the functionality added by this PR - creating a map of loggroup:tags for all task definitions in the aws account. 
Tested on investigations task definitions - you can see some logs [here](https://logs.gutools.co.uk/s/investigations/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-2h,to:now))&_a=(columns:!(message,app),filters:!(),index:'3501e690-a763-11eb-882c-5b432fbcaa69',interval: …

Support Auto Tagging ECS Tasks

---

riff-raff.yaml

Previously we saw a large production incident when this project was deployed to an unsupported stage (CODE). This commit takes advantage of the new 'allowedStages' RiffRaff feature to ensure we do not deploy to CODE or other, non-PROD, stages again.
Note, there is currently a deploy restriction to CODE in RiffRaff already, so this adds extra defence on top of that.

Limit deployments to PROD

---

src/config.ts
src/shipLogEntries.ts
template.yaml

Remove the optional `KinesisStreamRole` parameter from the CloudFormation template.
An analysis (see below) of instances of this stack show the following accounts have this set:
- workflow
- media-service
- cmsFronts
These stacks belong to the Editorial Tools team (cc @guardian/digital-cms).
Only they have set the parameter because the logging setup within Editorial Tools was a little different from most. The team used to have a single logging stream that was shared between their various AWS accounts; apps that ran in a different account from the stream assumed a role to gain permission to write to it.
The team have since updated this, favouring a stream per account. This can be confirmed by observing the value of the `KinesisStreamArn` parameter - the value maps to a stream in the …

feat!: Remove ability to assume a role to write to kinesis

---

scripts/ci.sh
src/build-info.ts
src/shipLogEntries.ts

Further augment the log message in Central ELK with information about the version of this app. This will help with debugging.
Inspired by [tools-index](https://github.com/guardian/tools-index/blob/1543179dab10d0ce1f3f1280405cf3bdf26046b0/.github/workflows/ci.yml#L47).
An alternative to this could be to add this information as tags in AWS. However, this would mean each deployment of this app would incur the cost of a CloudFormation deployment, even if no code changes to the infrastructure were made. See also: https://github.com/guardian/cdk/pull/1244.
I've deployed this to the DevX account and can see the new log markers appearing:
It's easier to debug changes to this application.
There's a risk that future changes to `build-info.ts` are not reflected in `ci.sh`. Hopefully the inline …

feat: Add build info markers to log lines

---

src/app.ts
src/config.ts
src/structuredFields.ts
template.yaml

As no instance of this stack sets this value to `false`, we can remove it and simplify the app. This is done for similar purposes to #153, namely to make a CDK migration easier.
I've checked each instance of this application and confirmed they all have `OptionLowerFirstCharOfTags` set to `true`.
Less code!
I can't work out why one would set this parameter to false (it was added as part of the [initial commit](https://github.com/guardian/cloudwatch-logs-management/commit/f03df0b3e5c44d76ffcf9f38edbf6fff972b5556#diff-1363ef5ce8886100842332c97163aad7934237e1fe49b5d40422b45fdc30f38eR33)). That is, we might break some workflow.

feat!: Remove redundant `OptionLowerFirstCharOfTags` CFN parameter

---

src/config.ts
template.yaml

Follows #155.
As no instance of this stack has customised this parameter, we can drop it to simplify a migration to CDK.

feat!: Remove `CloudWatchLogsFilterName` CFN Parameter

---

packages/app/src/handlers/index.ts
packages/app/src/handlers/set-log-shipping.ts
packages/app/src/handlers/set-retention.ts
packages/app/src/handlers/ship-log-entries.ts
packages/cdk/lib/__snapshots__/cloudwatch-logs-management.test.ts.snap
packages/cdk/lib/cloudwatch-logs-management.ts

In this change, we create a `handlers` directory to house the entry points for the lambdas, in the hope of increasing maintainability after observing it being difficult to know where to start.
It's worth noting that the layout of this service is different from most others. This service produces a mono-zip with multiple entry points. An alternative to this change could be to produce an artifact per lambda.
UPDATE: I noticed a number of errors in the logs for the `set-log-shipping` lambda, referencing missing configuration. Also included in this change is a fix for this. I'm not sure why we've not seen it in the past yet though.
I've deployed this to the deployTools account, and can [see logs](https://logs.gutools.co.uk/s/devx/goto/812fcd90-77d0-11ed-bf9b-0115a646a520) appearing in Central …

refactor: Add explicit handlers directory for clarity

---

packages/app/src/config.ts

Currently we configure AWS retries by reading the `AWS_RETRIES` env var, defaulting to `10`. `AWS_RETRIES` is not a [runtime environment variable](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime), and we're not explicitly setting it. That is, we always hit the fallback value.
In this change, we simplify this by just setting retries explicitly to 10.
n/a
n/a
n/a

refactor: Simplify retry config

---

.github/workflows/ci.yml
scripts/ci.sh

Move CI providers from TeamCity to GitHub Actions. This is mainly driven by #209 not building in TeamCity due to TeamCity failing to run Node 18.
Initially keeping the CI steps the same as TeamCity's, that is using the NPM module `@guardian/node-riffraff-artifact`. We can move to `guardian/actions-riff-raff` separately.
> **Note**
> The branch protection rules on the repo are configured to require TeamCity to pass, however I've paused the builds there. Once approved, I'll update the branch protection rules.
Observation of the artifacts in Riff-Raff:
- [`main`](https://riffraff.gutools.co.uk/deployment/request/deployFiles?projectName=tools%3A%3Acloudwatch-logs-management&id=488)
- [this branch](https://riffraff.gutools.co.uk/deployment/request/deployFiles?projectName=tools%3A%3Acloudwatch-l …

ci: Move CI to GitHub Actions

---

.github/workflows/ci.yml

Create a build when `main` is pushed to (i.e. on merge), so that CD is triggered. This was missed in https://github.com/guardian/cloudwatch-logs-management/pull/211.

ci: Run CI when `main` is updated

---

packages/app/src/handlers/set-log-shipping.ts
packages/app/src/handlers/set-retention.ts
packages/app/src/handlers/ship-log-entries.ts

This PR moves the config fetching (from the env) to the relevant lambda handlers. Before config was fetched at the top level of each of the files which define the lambda handlers. This means that the config was fetched when the file was included, even if the handler wasn't run. So when running the set-retention lambda, for example, we were seeing errors because the config for the ship-log-entries lambda wasn't available.

Move config fetching into lambda handlers

---

packages/cdk/bin/cdk.ts

We would like to set log retention and log shipping to a new Personalisation account.

Add Personalisation AWS account

---

packages/cdk/bin/cdk.ts

We have a few experimental lambdas in the Playground account, and it'll be nice to observe their logs in Central ELK.
I've [deployed](https://riffraff.gutools.co.uk/deployment/view/a83ea275-1a7d-4d92-87b8-c60bc6f130fe) this, triggered a [lambda](https://github.com/guardian/examples/tree/example-typescript-lambda), and found it's [logs in Central ELK](https://logs.gutools.co.uk/goto/ea4e3010-5145-11ee-913c-1f0e93d001da) (might need to expand the time frame).
Logs for lambdas in the Playground account will appear in Central ELK, and their CloudWatch log groups' retention period is set to 14 days.
N/A.

feat: Provision this service into the Playground account

---

packages/app/src/s3.ts

Switch the method used to retrieve the string contents of the `structured-fields.json` file from `toString()` to `transformToString()`.
After #276 was merged, we move from using v2 to v3 of the AWS SDK. However, in v3 of the SDK the `toString` method called on an S3 response body no longer returns the body, but instead just `[Object] object` ([see this comment for some more context](https://github.com/aws/aws-sdk-js-v3/issues/1877#issuecomment-1287263428)). This causes `JSON.parse` to throw an error, which prevents the structured fields stored on S3 from being included as fields in ELK. This error is handled in one of the calling functions, so logs are still shipped to S3, just without the fields.
I deployed this change to the developer playground account, and re-enabled Cloudwatch …

fix: Parsing of structured fields from S3

---

.github/dependabot.yml

Create groups to update the AWS SDK, and code quality tools.
This should reduce the number of PRs. These would become one:

chore(dependabot): Add group configuration

---

packages/cdk/bin/cdk.ts

Content Production are migrating FTP clients to a managed SFTP service using AWS Transfer. At present, the logs for this are not shipped to central ELK, which complicates troubleshooting.
This PR adds the AWS transfer prefix (as well as the existing Lambda one) to the Media Service account to enable shipping of logs
Tested in Media Service Account - logs now visible in Central ELK
Transfer logs should be available in central ELK
SHould be fine

add aws transfer to media service log shipping prefixes

---

packages/cdk/bin/cdk.ts

So that we can ship logs for the new gudocs app

Add interactives aws account to cloudwatch logs management

---

README.md
packages/cdk/bin/cdk.ts

- Reword the readme slightly to use deployment-resource-stack instead of just stack when thats what we mean.
- Add instructions to readme for adding deployment-resource-stacks with logs that contain PII data.
- Add comments to cdk.ts that specify what we mean by 'stack' in this file
- Add comment above [retentionOnlyStacks](https://github.com/guardian/cloudwatch-logs-management/blob/61c3ad31cd9ee7977cc43dd08cb2fdbf50e462ff/packages/cdk/bin/cdk.ts#L13) to explain what its for and recommend it for stacks that have logs with PII data.
[A stack by any other name...](https://github.com/guardian/cloudwatch-logs-management/pull/346/commits/8c6858a9b21aad7c1020a135a7e7e41ab64fe039)
The readme uses the word stack to mean both cloudformation stack and deployment-resource-stack in different places. …

Update README.md to clarify when we mean deployment-resource-stack rather than cloudformation stack

---

packages/cdk/bin/cdk.ts

Adds a new logs management stack to the editorial-feeds account, to provide log shipping for new lambdas in that account.
N/A - happy to take suggestions
Logs from new lambdas in the editorial-feeds account are available in central ELK

Add a logs management stack for the editorial-feeds account

---

packages/cdk/bin/cdk.ts

We are introducing some fargate tasks to the transcription service (https://github.com/guardian/transcription-service). This change will ensure that the logs from those tasks are shipped to central ELK.
None

Add transcription-service prefix to investigations logs

---

packages/cdk/bin/cdk.ts

Deploys this service to the hiring-and-onboarding account to allow for lambda logs to be shipped to Central ELK.

Deploy service to the hiring-and-onboarding account
